### ISSUE TITLE
Then you realllly shouldn't be here, bud.

### ISSUE THREAD

**Issue by Fredoflo** [rverseTeam/rverse2#47]
Miiverse

**Comment by Frocat64** [comment]
could you please stop with this.
I have Notifications on because i want to know if something interesting is going on but this is just annoying! If you have an Issue write a real one with your Issue but just making seven Issues and one Pull-Request with no sense like just writing “Miiverse” or Reverting a language which is really just unnecessary that just makes no sense. I don’t wanna sound rude but its just really annoying!
